### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Eggwise** [zachgarwood/ember-syncano#4]
created a new ember app
installed ember syncano

created a test model with only a title, in syncano & ember

in my route 

> routes/test.js

```
import Ember from 'ember';

export default Ember.Route.extend({


  model(){

    const all_test = this.store.findAll('test');
    console.log(all_test);
    return all_test;

  }
});

```

i get the error:

```

ember.debug.js:30287 Error while processing route: test Cannot read property 'please' of undefined TypeError: Cannot read property 'please' of undefined
    at http://localhost:4200/assets/vendor.js:84172:30
    at Object.initializePromise (http://localhost:4200/assets/vendor.js:61533:7)
    at new Promise (http://localhost:4200/assets/vendor.js:63128:21)
    at Class.findAll (http://localhost:4200/assets/vendor.js:84171:14)
    at _findAll (http://localhost:4200/assets/vendor.js:76034:27)
    at Class._fetchAll (http://localhost:4200/assets/vendor.js:74714:121)
    at Class.findAll (http://localhost:4200/assets/vendor.js:74687:19)
    at Class.model (http://localhost:4200/assets/guntisbergen-frontend.js:255:37)
    at Class.deserialize (http://localhost:4200/assets/vendor.js:39073:19)
    at Object.applyHook (http://localhost:4200/assets/vendor.js:61186:30)
    at Object.runSharedModelHook (http://localhost:4200/assets/vendor.js:59171:33)
    at Object.getModel (http://localhost:4200/assets/vendor.js:59402:19)
    at http://localhost:4200/assets/vendor.js:61039:17
    at tryCatch (http://localhost:4200/assets/vendor.js:61483:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:61498:15)
    at publish (http://localhost:4200/assets/vendor.js:61466:9)logError @ ember.debug.js:30287error @ ember.debug.js:30230triggerEvent @ ember.debug.js:30365trigger @ ember.debug.js:50520trigger @ ember.debug.js:50324(anonymous function) @ ember.debug.js:50136tryCatch @ ember.debug.js:50950invokeCallback @ ember.debug.js:50965publish @ ember.debug.js:50933publishRejection @ ember.debug.js:50868(anonymous function) @ ember.debug.js:40413invoke @ ember.debug.js:990flush @ ember.debug.js:1054flush @ ember.debug.js:862end @ ember.debug.js:176run @ ember.debug.js:298join @ ember.debug.js:318run.join @ ember.debug.js:23767(anonymous function) @ ember.debug.js:23830mightThrow @ jquery.js:3570process @ jquery.js:3638
ember.debug.js:19157 TypeError: Cannot read property 'please' of undefined
    at syncano.js:82
    at Object.initializePromise (ember.debug.js:51000)
    at new Promise (ember.debug.js:52595)
    at Class.findAll (syncano.js:81)
    at _findAll (finders.js:136)
    at Class._fetchAll (store.js:1201)
    at Class.findAll (store.js:1174)
    at Class.model (test.js:6)
    at Class.deserialize (ember.debug.js:28540)
    at Object.applyHook (ember.debug.js:50653)
    at Object.runSharedModelHook (ember.debug.js:48638)
    at Object.getModel (ember.debug.js:48869)
    at ember.debug.js:50506
    at tryCatch (ember.debug.js:50950)
    at invokeCallback (ember.debug.js:50965)
    at publish (ember.debug.js:50933)
```

script crashes here 

> syncano.js

```
    /**
     * Used by the store to retrieve the entire collection of records of a
     * certain model.
     */
    findAll: function findAll(store, type) {
      var instanceName = this.get('syncano.instanceName');
      var connection = this.get('syncano.connection');
      return new _ember['default'].RSVP.Promise(function (resolve, reject) {

   >>UNDERNEATH HERE, LINE 82    
        connection.DataObject.please().list({ className: type.modelName, instanceName: instanceName }).then(function (data) {
          _ember['default'].run(null, resolve, data);
        })['catch'](function (error) {
          _ember['default'].run(null, reject, error);
        });
      });
    },

```

syncano can't seem to make a connection...
Checked my enviroment config, tried different api keys, & instances.

> package.json

```
{
  "name": "test",
  "version": "0.0.0",
  "description": "Small description for test goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.8.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.1.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.8.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-syncano": "0.2.0",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1"
  }

}
```

i really need to make an ember app quick.. any clues what is going wrong?

**Comment by Eggwise** [comment]
i fixxed the bug, testing it now. coming soon with a PR
